version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "steamroller-airmash"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "steamroller-airmash"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "steamroller-airmash"
