version: 2
jobs:
  fetch:
    working_directory: ~/build
    docker: 
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - restore_cache:
        key: fetch-cache-{{ checksum "Cargo.lock" }}
      - run: Fetch dependencies
        name: cargo fetch
      - save_cache:
        key: fetch-cache-{{ checksum "Cargo.lock" }}
        paths:
          - ~/cargo

  build:
    working_directory: ~/build
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run:
        name: Save rustc version
        run: rustc -V > ~/rustc.version
      - restore_cache:
        key: fetch-cache-{{ checksum "Cargo.lock" }}
      - restore_cache:
        key: build-cache-{{ checksum "Cargo.lock" }}-{{ checksum "~/rustc.version" }}
      - run:
        name: Build Package
        command: cargo +nightly build
      - save_cache:
        key: build-cache-{{ checksum "Cargo.lock" }}-{{ checksum "~/rustc.version" }}
        paths:
          - target
  test:
    working_directory: ~/build
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - restore_cache:
        key: fetch-cache-{{ checksum "Cargo.lock" }}
      - run:
        name: Test Package
        command: cargo +nightly test

workflows:
  version: 2
  build_and_test:
    jobs:
      - fetch
      - build:
        requires:
          - fetch
      - test:
        requires:
          - fetch