[package]
name = "airmash-server"
version = "0.0.1"
authors = ["STEAMROLLER"]
license = "Apache-2.0 OR MIT"
publish = false
repository = 'https://github.com/steamroller-airmash/airmash-server'


[features]
# If enabled, set TCP_NODELAY on incoming connections
nodelay = []
# Enable looking for the X-Forwarded-For header
# when determining client IP address
proxied = []
# Turn on bot blocking settings
block-bots = []

[dependencies]
simple_logger = "*"
log = "0.4.1"
specs = { version = "*", features = ["nightly"] }
specs-derive = "*"
dimensioned = "*"
lazy_static = "*"
fnv = "*"
rand = "0.4"
shred = "*"
shred-derive = "*"
shrev = "*"
tokio = "*"
tokio-core = "*"
rayon = "1.0"
htmlescape = "*"
hibitset = "*"
bounded-queue = { path = "../bounded-queue" }
special-map = { path = "../special-map" }
protocol-v5 = { path = "../protocol-v5" }
serde = { version = "*", features = ["derive"] }
serde_json = "*"

[dependencies.protocol-common]
path = "../protocol-common"
features = ["specs"]

[dependencies.uuid]
version = "*"
features=["v5"]

# This and websocket must be versioned together
[dependencies.hyper]
version = "0.10"

[dependencies.websocket]
version = "0.20"
default-features = false
features = [ "async", "async-ssl" ]
