[package]
name = "airmash-server"
version = "0.0.1"
authors = ["STEAMROLLER"]
license = "Apache-2.0 OR MIT"
publish = false
repository = 'https://github.com/steamroller-airmash/airmash-server'
edition = "2018"

[features]
# Have logging on by default, it doesn't do anything
# unless the environment variable is on
default = [ ]
# If enabled, set TCP_NODELAY on incoming connections
nodelay = []
# Enable looking for the X-Forwarded-For header
# when determining client IP address
proxied = []
# Turn on bot blocking settings
block-bots = []

[dependencies]
log = "0.4"
# When specs updates to shred 0.8.0 this will need to be updated as well
shred = "0.7"
shred-derive = "0.5"
specs = { version = "0.14.3", features = ["nightly"] }
specs-derive = "0.4"
dimensioned = "0.7"
lazy_static = "1.0"
rand = "0.4"
shrev = "1.1"
rayon = "1.0"
htmlescape = "0.3"
hibitset = "0.5"
bounded-queue = { path = "../bounded-queue" }
special-map = { path = "../special-map" }
airmash-protocol-v5 = { git="https://github.com/steamroller-airmash/airmash-protocol-v5"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ws = "0.8"
hashbrown = "0.5"
parking_lot = "0.7"

[dependencies.sentry]
optional = true
version = "*"

[dependencies.airmash-protocol]
version = "0.3"
features = ["specs"]
git = "https://github.com/steamroller-airmash/airmash-protocol-rs"

[dependencies.uuid]
version = "0.7"
features=["v5"]
