[package]
name = "airmash-server-ctf"
version = "0.0.1"
authors = ["STEAMROLLER"]
license = "Apache-2.0 OR MIT"
publish = false
repository = 'https://github.com/steamroller-airmash/airmash-server'
edition = "2018"

[features]

[dependencies]
# When specs updates to shred 0.8.0 this will need to be updated as well
shred = "0.7"
shred-derive = "0.5"
specs = { version = "0.14.3", features = ["nightly"] }
shrev = "*"
fnv = "*"
log = "*"
rand = "0.4"
specs-derive = "*"
lazy_static = "*"
htmlescape = "*"
env_logger = "*"
serde = { version = "*", features = [ "derive" ]}
serde-deserialize-over = { git="https://github.com/steamroller-airmash/serde-deserialize-over" }
serde_json = "*"
clap = "*"

[dependencies.sentry]
optional = true
version = "*"

[dependencies.airmash-server]
path = '../server'
# Enable looking for X-Forwarded-For within the request
features = [ "proxied" ]
