[package]
name = "airmash-server-ctf"
version = "0.0.1"
authors = ["STEAMROLLER"]
license = "Apache-2.0 OR MIT"
publish = false
repository = 'https://github.com/steamroller-airmash/airmash-server'

[dependencies]
specs = "*"
shrev = "*"
shred = { version = "*", features= ["nightly"] }
fnv = "*"
log = "0.4"
rand = "0.4"
specs-derive = "*"
shred-derive = "*"
lazy_static = "*"
htmlescape = "*"
env_logger = "*"
serde = { version = "*", features = [ "derive" ]}
serde_json = "*"

[dependencies.airmash-server]
path = '../server'
# Enable looking for X-Forwarded-For within the request
features = [ "proxied" ]
