[package]
name = "protocol-v5"
version = "0.0.1"
authors = ["STEAMROLLER"]
license = "Apache-2.0 OR MIT"
publish = false
repository = 'https://github.com/steamroller-airmash/airmash-server'

[dependencies]
protocol-common = { path="../protocol-common" }
