name: Auto-merge compatible dependabot PRs
on:
  pull_request:

jobs:
  auto-merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          command: squash and merge
          github-token: ${{ secrets.mytoken }}
