name: Auto-merge compatible dependabot PRs
on: pull_request

permissions:
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:        
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr comment "$PR_URL" -b "@dependabot squash and merge"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
