on: [push, pull_request]

name: ci-linux

jobs:
  build_and_test:
    name: airmash
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        toolchain: [stable, beta]
        experimental: [false]
        include:
          - toolchain: nightly
            experimental: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: actions-rs/cargo@v1
        with:
          command: test
