
on:
  workflow_dispatch:
  push:

name: docker

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ctf, ffa, base]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/${{ github.repository_owner }}/server-${{ matrix.target }}:latest
          build-args: |
            TARGET=${{ matrix.target }}
          push: ${{ github.ref == 'refs/heads/master' }}

