
on: [push]

name: docker

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ctf, ffa, base]
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: |
          docker build . \
            -f .github/assets/dockerfile \
            --build-arg TARGET=${{ matrix.target }}
